name: Deploy Docs

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install sphinx sphinx-rtd-theme sphinx_copybutton
      - run: make -C docs html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs/_build/html